## Task 1: Data Collection & Dataset Understanding

In [ ]:
import pandas as pd 
df=pd.read_excel("../datasets/week1.xlsx")

In [ ]:
df.head(5)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
df.dtypes

OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

In [ ]:
df.size

16800

In [ ]:
df.shape

(1200, 14)

In [ ]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

## Task 2: Data Cleaning & Preprocessing

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
#  Handle missing values
# coupon code has missing values

df["CouponCode"].fillna("No Coupon", inplace=True)

# not all customers have coupn code, so we can fill missing values with "No Coupon"

C:\Users\noors\AppData\Local\Temp\ipykernel_31176\4040125476.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["CouponCode"].fillna("No Coupon", inplace=True)

In [ ]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [ ]:
# Format data correctly
df["Date"] = pd.to_datetime(df["Date"], errors="coerce").dt.date
# converted to date objects removed time component

In [ ]:
df["Date"]

0       2023-01-04
1       2024-08-23
2       2024-02-27
3       2023-10-15
4       2025-05-08
           ...
1195    2024-06-20
1196    2024-03-04
1197    2023-07-13
1198    2024-08-22
1199    2023-06-11
Name: Date, Length: 1200, dtype: object

In [ ]:
df.to_excel("../datasets/week1_cleaned.xlsx", index=False)

## Task 3: Exploratory Data Analysis (EDA)

In [1]:
import pandas as pd
df1 = pd.read_excel("../datasets/week1_cleaned.xlsx")

In [2]:
df1.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [4]:
df1.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

as we can see the missing values are removed. The data columns are right skewed, means the std is less than the mean which means few outliers pull the mean high. We will try to remove outliers from the data and make dist normal.

In [5]:
num_cols = ["Quantity", "UnitPrice", "ItemsInCart", "TotalPrice"]

In [6]:
df1[num_cols].agg(["mean", "median", "std", "var", "skew", "kurt"])
#> 0  → right skew, < 0  → left skew, ≈ 0  → symmetric

        Quantity     UnitPrice  ItemsInCart     TotalPrice
mean    2.945833    356.412750     5.485000    1053.968300
median  3.000000    364.210000     5.000000     823.615000
std     1.407557    197.177146     2.281983     819.856558
var     1.981217  38878.827068     5.207448  672164.776294
skew    0.027922     -0.026512     0.000877       0.891359
kurt   -1.294596     -1.191011    -0.708552      -0.040415

we can see that the totalPrice column is highly right skewed, which means there are few outliers that pull the mean high. We can try to remove outliers from the data and make the distribution normal.

In [7]:
# product analysis to understand which products are most popular and generate the most revenue. This can help in inventory management and marketing strategies.
product_quantity= ( df1.groupby("Product")["Quantity"].sum().sort_values(ascending=False))

print(product_quantity)

Product
Chair      562
Printer    542
Laptop     535
Desk       508
Tablet     497
Monitor    480
Phone      411
Name: Quantity, dtype: int64

In [8]:
product_revenue = df1.groupby("Product")["TotalPrice"].sum().sort_values(ascending=False)

print(product_revenue)

Product
Chair      195620.11
Printer    195612.61
Laptop     192126.56
Tablet     186568.95
Monitor    175651.41
Desk       167459.93
Phone      151722.39
Name: TotalPrice, dtype: float64

In [9]:
customer_orders= ( df1['CustomerID'].value_counts().sort_values(ascending=False))
customer_orders.head(10)

CustomerID
C38840    2
C97593    2
C98474    2
C91155    2
C35852    2
C56969    2
C14847    2
C70659    2
C94569    2
C21191    2
Name: count, dtype: int64

In [10]:
customer_orders.describe()

count    1189.000000
mean        1.009251
std         0.095779
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000
Name: count, dtype: float64

In [11]:
corr = df1[num_cols].corr()

print(corr)

             Quantity  UnitPrice  ItemsInCart  TotalPrice
Quantity     1.000000   0.014553     0.650061    0.615251
UnitPrice    0.014553   1.000000     0.000602    0.717081
ItemsInCart  0.650061   0.000602     1.000000    0.392540
TotalPrice   0.615251   0.717081     0.392540    1.000000

In [12]:
# outliers finding using IQR method
for col in num_cols:

    Q1 = df1[col].quantile(0.25)
    Q3 = df1[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df1[(df1[col] < lower) | (df1[col] > upper)]

    print(f"{col}: {len(outliers)} outliers")

Quantity: 0 outliers
UnitPrice: 0 outliers
ItemsInCart: 0 outliers
TotalPrice: 8 outliers

In [13]:
outliers["TotalPrice"]

107     3353.75
326     3352.40
328     3370.20
469     3384.90
632     3390.80
789     3456.40
1065    3334.00
1122    3390.95
Name: TotalPrice, dtype: float64

In [14]:
df2=df1.drop(outliers.index, inplace=False)

In [15]:
df2["TotalPrice"].mean()

np.float64(1038.3628859060402)

u can see how much the 8 outliers in total price were effecting the mean , removal of them took mean down from so high to avg value

In [16]:
df2["TotalPrice"].std()

800.0697050640459

In [ ]:
df2.to_excel("../datasets/week1_outliers_removed.xlsx", index=False)

In [ ]:
# revenue analysis